/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVolunteersRouteImport } from './routes/_authenticated/volunteers'
import { Route as AuthenticatedVenueRouteImport } from './routes/_authenticated/venue'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthenticatedSustainabilityRouteImport } from './routes/_authenticated/sustainability'
import { Route as AuthenticatedShiftLogRouteImport } from './routes/_authenticated/shift-log'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMultiStadiumRouteImport } from './routes/_authenticated/multi-stadium'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedFoodWashroomsRouteImport } from './routes/_authenticated/food-washrooms'
import { Route as AuthenticatedDigitalTwinRouteImport } from './routes/_authenticated/digital-twin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvFeedRouteImport } from './routes/_authenticated/cv-feed'
import { Route as AuthenticatedCrowdRouteImport } from './routes/_authenticated/crowd'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedAnomaliesRouteImport } from './routes/_authenticated/anomalies'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVolunteersRoute = AuthenticatedVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenueRoute = AuthenticatedVenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSustainabilityRoute =
  AuthenticatedSustainabilityRouteImport.update({
    id: '/sustainability',
    path: '/sustainability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShiftLogRoute = AuthenticatedShiftLogRouteImport.update({
  id: '/shift-log',
  path: '/shift-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMultiStadiumRoute =
  AuthenticatedMultiStadiumRouteImport.update({
    id: '/multi-stadium',
    path: '/multi-stadium',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodWashroomsRoute =
  AuthenticatedFoodWashroomsRouteImport.update({
    id: '/food-washrooms',
    path: '/food-washrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDigitalTwinRoute =
  AuthenticatedDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvFeedRoute = AuthenticatedCvFeedRouteImport.update({
  id: '/cv-feed',
  path: '/cv-feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrowdRoute = AuthenticatedCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnomaliesRoute = AuthenticatedAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/anomalies': typeof AuthenticatedAnomaliesRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/crowd': typeof AuthenticatedCrowdRoute
  '/cv-feed': typeof AuthenticatedCvFeedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/food-washrooms': typeof AuthenticatedFoodWashroomsRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/multi-stadium': typeof AuthenticatedMultiStadiumRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/shift-log': typeof AuthenticatedShiftLogRoute
  '/sustainability': typeof AuthenticatedSustainabilityRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/venue': typeof AuthenticatedVenueRoute
  '/volunteers': typeof AuthenticatedVolunteersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/anomalies': typeof AuthenticatedAnomaliesRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/crowd': typeof AuthenticatedCrowdRoute
  '/cv-feed': typeof AuthenticatedCvFeedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/food-washrooms': typeof AuthenticatedFoodWashroomsRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/multi-stadium': typeof AuthenticatedMultiStadiumRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/shift-log': typeof AuthenticatedShiftLogRoute
  '/sustainability': typeof AuthenticatedSustainabilityRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/venue': typeof AuthenticatedVenueRoute
  '/volunteers': typeof AuthenticatedVolunteersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/anomalies': typeof AuthenticatedAnomaliesRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/crowd': typeof AuthenticatedCrowdRoute
  '/_authenticated/cv-feed': typeof AuthenticatedCvFeedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/_authenticated/food-washrooms': typeof AuthenticatedFoodWashroomsRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/multi-stadium': typeof AuthenticatedMultiStadiumRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/shift-log': typeof AuthenticatedShiftLogRoute
  '/_authenticated/sustainability': typeof AuthenticatedSustainabilityRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/_authenticated/venue': typeof AuthenticatedVenueRoute
  '/_authenticated/volunteers': typeof AuthenticatedVolunteersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/anomalies'
    | '/copilot'
    | '/crowd'
    | '/cv-feed'
    | '/dashboard'
    | '/digital-twin'
    | '/food-washrooms'
    | '/incidents'
    | '/multi-stadium'
    | '/notifications'
    | '/security'
    | '/shift-log'
    | '/sustainability'
    | '/transport'
    | '/venue'
    | '/volunteers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/anomalies'
    | '/copilot'
    | '/crowd'
    | '/cv-feed'
    | '/dashboard'
    | '/digital-twin'
    | '/food-washrooms'
    | '/incidents'
    | '/multi-stadium'
    | '/notifications'
    | '/security'
    | '/shift-log'
    | '/sustainability'
    | '/transport'
    | '/venue'
    | '/volunteers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/anomalies'
    | '/_authenticated/copilot'
    | '/_authenticated/crowd'
    | '/_authenticated/cv-feed'
    | '/_authenticated/dashboard'
    | '/_authenticated/digital-twin'
    | '/_authenticated/food-washrooms'
    | '/_authenticated/incidents'
    | '/_authenticated/multi-stadium'
    | '/_authenticated/notifications'
    | '/_authenticated/security'
    | '/_authenticated/shift-log'
    | '/_authenticated/sustainability'
    | '/_authenticated/transport'
    | '/_authenticated/venue'
    | '/_authenticated/volunteers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/volunteers': {
      id: '/_authenticated/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof AuthenticatedVolunteersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venue': {
      id: '/_authenticated/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof AuthenticatedVenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sustainability': {
      id: '/_authenticated/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof AuthenticatedSustainabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift-log': {
      id: '/_authenticated/shift-log'
      path: '/shift-log'
      fullPath: '/shift-log'
      preLoaderRoute: typeof AuthenticatedShiftLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multi-stadium': {
      id: '/_authenticated/multi-stadium'
      path: '/multi-stadium'
      fullPath: '/multi-stadium'
      preLoaderRoute: typeof AuthenticatedMultiStadiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food-washrooms': {
      id: '/_authenticated/food-washrooms'
      path: '/food-washrooms'
      fullPath: '/food-washrooms'
      preLoaderRoute: typeof AuthenticatedFoodWashroomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digital-twin': {
      id: '/_authenticated/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AuthenticatedDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-feed': {
      id: '/_authenticated/cv-feed'
      path: '/cv-feed'
      fullPath: '/cv-feed'
      preLoaderRoute: typeof AuthenticatedCvFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crowd': {
      id: '/_authenticated/crowd'
      path: '/crowd'
      fullPath: '/crowd'
      preLoaderRoute: typeof AuthenticatedCrowdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anomalies': {
      id: '/_authenticated/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AuthenticatedAnomaliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnomaliesRoute: typeof AuthenticatedAnomaliesRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedCrowdRoute: typeof AuthenticatedCrowdRoute
  AuthenticatedCvFeedRoute: typeof AuthenticatedCvFeedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDigitalTwinRoute: typeof AuthenticatedDigitalTwinRoute
  AuthenticatedFoodWashroomsRoute: typeof AuthenticatedFoodWashroomsRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedMultiStadiumRoute: typeof AuthenticatedMultiStadiumRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedShiftLogRoute: typeof AuthenticatedShiftLogRoute
  AuthenticatedSustainabilityRoute: typeof AuthenticatedSustainabilityRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedVenueRoute: typeof AuthenticatedVenueRoute
  AuthenticatedVolunteersRoute: typeof AuthenticatedVolunteersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnomaliesRoute: AuthenticatedAnomaliesRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedCrowdRoute: AuthenticatedCrowdRoute,
  AuthenticatedCvFeedRoute: AuthenticatedCvFeedRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDigitalTwinRoute: AuthenticatedDigitalTwinRoute,
  AuthenticatedFoodWashroomsRoute: AuthenticatedFoodWashroomsRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedMultiStadiumRoute: AuthenticatedMultiStadiumRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedShiftLogRoute: AuthenticatedShiftLogRoute,
  AuthenticatedSustainabilityRoute: AuthenticatedSustainabilityRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedVenueRoute: AuthenticatedVenueRoute,
  AuthenticatedVolunteersRoute: AuthenticatedVolunteersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
